* The Magicians Fan App - An Executable Memoir

** An Exercise In Literate Programming

by Colin Jaffe

*** Chapter 1 - Wait, What Am I Reading Again?

#+begin_src json
  {
    "season": 1,
    "episode": 1,
    "explicit": true,
    "id": 3,
    "lines": [
      {
        "speaker": "Henry Fogg",
        "line": "You want to go back to Columbia? That pointless, miasmic march to death you call life? Family that never calls and friends that don't really get you and feeling alone and wrong until it crushes you?"
      },
      {
        "speaker": "Quentin",
        "line": "No."
      },
      {
        "speaker": "Henry Fogg",
        "line": "Then quit dicking around!"
      },
      {
        "speaker": "Quentin",
        "line": "Stop it."
      },
      {
        "speaker": "Henry Fogg",
        "line": "Do some goddamn magic!"
      }
    ]
  },
#+end_src

What follows is a story about magic. Black magic, white magic, all the beautiful colors in between, and the grey magic that covers all the other magic in a miasma of forgettable boredom.

What follows is /also/ a story about code. How we program these machines, how they program us, how they program each other, and how /we/ program each other. How magical and mundane it all is—how easy it is to get lost in the algorithmic and recursive maze of software engineering, a secret labyrinth whose high walls of  ones and zeros are a marvel of architectural vision and unseeing exclusion.

What follows is /also/ also an executable computer program. The quote at the top of this introduction isn't just an epigraph, but part of the program that creates an app about The Magicians TV Show. This book is a spellbook, and if you read its code aloud in the light of the full moon in a mirror held over your shoulder—or, only slightly easier, compile it with the text editor Emacs—then out pops the app you never knew you didn't want.

What follows is /also/ also */also/* a story about the TV show The Magicians—its nerdy energy, its clever, quotable characters, and whether its attempts to subvert stupid fantasy tropes without being stupid itself actually work. If you don't love the show now, you'll /really/ not love it after listening to me talk about it!

And that self-deprecating aside brings us to what this story is mostly about: me. Like all good magic and all good code, this story is written to produce an effect /and/ to communicate its intent, an attempt to make the world a slightly more interesting place by shouting "Me me me me! Me? Look at ME!" in an original way. It's a story about love and loss, as they all are, and a step-by-step guide to misunderstanding yourself for a couple decades—all who wander are not lost, but #why-not-both? It's a silly story full of silly mistakes and silly jokes and silly people being the exact same sort of silly as their parents despite /clearly/ trying to straighten up and why does no one /see/ that. It's a story about a person's life that, like many lives halfway over, can feel like it should maybe begin now? And also that it's basically over already? And how to maybe be okay with all that?

To sum it all up, you're reading a treatise comparing magic with code and storytelling, wrapped in memoir and compilable to the computer source code for an app about a TV show.

As Quentin says when they blow a hole in the door with light-bending magic: it's Phosphoromancy, bitches!

Welcome to /The Magicians Fan App/.

#+begin_src json
  {
    "season": 1,
    "episode": 3,
    "explicit": true,
    "id": 16,
    "lines": [
      {
        "speaker": "Quentin",
        "line": "Phosphoromancy, bitches."
      }
    ]
  },
#+end_src
