* The Magicians Fan App - An Executable Memoir

** An Exercise In Literate Programming

by Colin Jaffe

*** Chapter 1 - Wait, What Am I Reading Again?

#+begin_src json
  {
    "season": 1,
    "episode": 1,
    "explicit": true,
    "id": 3,
    "lines": [
      {
        "speaker": "Henry Fogg",
        "line": "You want to go back to Columbia? That pointless, miasmic march to death you call life? Family that never calls and friends that don't really get you and feeling alone and wrong until it crushes you?"
      },
      {
        "speaker": "Quentin",
        "line": "No."
      },
      {
        "speaker": "Henry Fogg",
        "line": "Then quit dicking around!"
      },
      {
        "speaker": "Quentin",
        "line": "Stop it."
      },
      {
        "speaker": "Henry Fogg",
        "line": "Do some goddamn magic!"
      }
    ]
  },
#+end_src

This story is weird.

This is a story about magic. Black magic, white magic, all the beautiful colors in between, and the grey magic that covers all the other magic in a miasma of forgettable boredom.

This is /also/ a story about code. How we program these machines on our desks and laps and in our pockets, how they program us, how they program /each other/, and how /we/ program each other. How magical and mundane it all is—how easy it is to get lost in the algorithmic and recursive maze of software engineering, a secret labyrinth whose high walls of ones and zeros are a marvel of architectural vision and unseeing exclusion. This is a story about programs and programmers and de-programmers and, the worst kind of all: literate programmers.

This is /also/ also a story about the TV show The Magicians—its nerdy energy, its clever, quotable characters, and whether its attempts to subvert stupid fantasy tropes without being stupid itself actually work. This is another springboard; there's a lot to unpack here, in this show about grad students trying to figure out their lives and maybe occasionally study something. If you don't love the show now, don't worry—you'll /really/ not love it after listening to me talk about it!

This is /also/ also ALSO an executable computer program. This story is a /spellbook/, and if you read its words aloud in the light of the gibbous moon in a mirror held over your shoulder—or, only slightly easier, compile it with the text editor Emacs—then out pops an app like an unasked-for genie. See,the quote at the top of this introduction isn't just an epigraph, but part of the code that creates an app about The Magicians TV Show. This story/piece/program/thing will contain /all/ the code for our app, and we'll chat about code in general and the interesting parts of this app, with explanations and asides and diversions. Like most codebases, you can skim the code or read it in full or ignore it altogether—the code is mostly here as a springboard for us on our journey through some dungeons and past a dragon or two until we've all Learned Something About Ourselves.

But yeah, it's also working code! So that's… nifty, I suppose.

And that self-deprecating aside brings us to what this story is /really/ about: me. Like all good magic/code/prose, this story is written to /hopefully/ cast/execute/sell, but its primary purpose is to communicate something to readers about what it's doing and why. And like all prose that is, at its heart, creative non-fiction, this story is an attempt to make the world a slightly more interesting place by telling people that they just /won't/ believe what happened to /me/, and in the telling connect with you. My story is a story about love and loss, as they all are, sure—I promise there'll be plenty of /that/ to go around—but with /maybe/ a /little/ less love and loss than your average personal story, replacing some love/loss with a step-by-step guide to growing to misunderstand yourself a /little/ less, gradually, over the course of a couple decades. All who wander are not lost, but we can do both as we journey through careers in balloon art and professional poker and serial monogamy and fatherhood and, most recently, a career in working your way down the tech job ladder, sliding slowly but surely down the eroding late-stage-capitalism hill to unemployment and (thus) writing this story.

This is a silly story full of silly mistakes and silly code and silly jokes and silly characters (real and imagined) being the exact same or exact opposite sorts of silly as their parents. It's a story about a person's life that, like many lives halfway over, can feel like it should maybe begin now? And also that it's basically over already? And how to maybe be okay with all that?

To sum it all up, you're reading a treatise comparing magic with code and storytelling, wrapped in memoir and compilable to the computer source code for an app about a TV show.

As the main character in the Magicians says when they blow a hole in the door with light-bending magic: it's Phosphoromancy, bitches!

Welcome to /The Magicians Fan App/.

#+begin_src json
  {
    "season": 1,
    "episode": 3,
    "explicit": true,
    "id": 16,
    "lines": [
      {
        "speaker": "Quentin",
        "line": "Phosphoromancy, bitches."
      }
    ]
  },
#+end_src
