* The Magicians Fan App - An Executable Memoir

** An Exercise In Literate Programming

by Colin Jaffe

*** Chapter 1 - Wait, What Am I Reading Again?

#+name: epigraph
#+begin_src json
  {
    "season": 1,
    "episode": 1,
    "explicit": true,
    "id": 3,
    "lines": [
      {
        "speaker": "Henry Fogg",
        "line": "You want to go back to Columbia? That pointless, miasmic march to death you call life? Family that never calls and friends that don't really get you and feeling alone and wrong until it crushes you?"
      },
      {
        "speaker": "Quentin",
        "line": "No."
      },
      {
        "speaker": "Henry Fogg",
        "line": "Then quit dicking around!"
      },
      {
        "speaker": "Quentin",
        "line": "Stop it."
      },
      {
        "speaker": "Henry Fogg",
        "line": "Do some goddamn magic!"
      }
    ]
  }
#+end_src

This story is weird.

This is a story about magic. Black magic, white magic, all the beautiful colors in between, and the grey magic that covers all the other magic in a miasma of forgettable boredom.

This is /also/ a story about code. How we program these machines on our desks and laps and in our pockets, how they program us, how they program /each other/, and how /we/ program each other. How magical and mundane it all is—how easy it is to get lost in the algorithmic and recursive maze of software engineering, a secret labyrinth whose high walls of ones and zeros are a marvel of architectural vision and unseeing exclusion. This is a story about programs and programmers and de-programmers and, the worst kind of all: literate programmers.

This is /also/ also a story about the TV show The Magicians—its nerdy energy, its clever, quotable characters, and whether its attempts to subvert stupid fantasy tropes without being stupid itself actually work. This is another springboard; there's a lot to unpack here, in this show about grad students trying to figure out their lives and maybe occasionally study something. If you don't love the show now, don't worry—you'll /really/ not love it after listening to me talk about it!

This is /also/ also ALSO an executable computer program. This story is a /spellbook/, and if you read its words aloud in the light of the gibbous moon in a mirror held over your shoulder—or, only slightly easier, compile it with the text editor Emacs—then out pops an app like an unasked-for genie. See, the quote at the top of this introduction isn't just an epigraph, but part of the code that creates an app about The Magicians TV Show. This story/piece/program/thing will contain /all/ the code for our app, and we'll chat about code in general and the interesting parts of this app, with explanations and asides and diversions. Like most codebases, you can skim the code or read it in full or ignore it altogether—the code is mostly here as a springboard for us on our journey through some dungeons and past a dragon or two until we've all Learned Something About Ourselves.

But yeah, it's also working code! So that's… nifty, I suppose.

So that brings us to what this story is /really/ about: me. Like all good magic/code/prose, this story is written to /hopefully/ cast/execute/sell, but its primary purpose is to communicate something to readers about what it's doing and why. And like all prose that is, at its heart, creative non-fiction, this story is an attempt to make the world a slightly more interesting place by telling people that they just /won't/ believe what happened to /me/, and in the telling connect with you. My story is a story about love and loss, as they all are, sure—I promise there'll be plenty of /that/ to go around—but with /maybe/ a /little/ less love and loss than your average personal story, replacing some love/loss with a step-by-step guide to growing to misunderstand yourself a /little/ less, gradually, over the course of a couple decades. All who wander are not lost, but we can do both as we journey through careers in balloon art and professional poker and serial monogamy and fatherhood and, most recently, a career in working your way down the tech job ladder, sliding slowly but surely down the eroding late-stage-capitalism hill to unemployment and (thus) writing this story.

This is a silly story full of silly mistakes and silly code and silly jokes and silly characters (real and imagined) being the exact same or exact opposite sorts of silly as their parents. It's a story about a person's life that, like many lives halfway over, can feel like it should maybe begin now? And also that it's basically over already? And how to maybe be okay with all that?

To sum it all up, you're reading a treatise comparing magic with code and storytelling, wrapped in memoir and compilable to the computer source code for an app about a TV show.

As the main character in the Magicians says when they blow a hole in the door with light-bending magic: it's Phosphoromancy, bitches!

Welcome to /The Magicians Fan App/.

#+name: phosphoromancy-bitches
#+begin_src json
  {
    "season": 1,
    "episode": 3,
    "explicit": true,
    "id": 16,
    "lines": [
      {
        "speaker": "Quentin",
        "line": "Phosphoromancy, bitches."
      }
    ]
  }
#+end_src

*** Appendix 1 - The Rest Of The Code

Here is the code for the app that I didn't (or haven't yet) discussed. It's the quotes I didn't find a use for but that still need to be in the app, or uninteresting parts of the code that didn't merit discussion, or whose discussion didn't quite fit in the story, or just stuff I haven't found time to write about yet but still want to /code/.

#+name: other-quotes
#+begin_src json
  {
    "quotes": [
      {
        "episode": "Unauthorized Magic",
        "explicit": false,
        "id": 0,
        "lines": [
          {
            "speaker": "Quentin",
            "line": "I mean, I get it."
          },
          {
            "speaker": "Dr. London",
            "line": "Get...?"
          },
          {
            "speaker": "Quentin",
            "line": "You're a kid, and your whole life's ahead of you, and you have these notions... about what life is... and... what it could be. But eventually you have to let all that go. So that's what I'm... That's what I'm going to do... that's what I'm doing. Um, it's a part of growing up... You know, selling the comic-book collection and getting serious."
          }
        ]
      },
      {
        "episode": "Unauthorized Magic",
        "explicit": false,
        "id": 1,
        "lines": [
          {
            "speaker": "Quentin",
            "line": "And, honestly, they probably take anyone conscious for philosophy."
          },
          {
            "speaker": "Julia",
            "line": "For philosophy, \"conscious\" is a detriment."
          }
        ]
      },
      {
        "episode": "Unauthorized Magic",
        "explicit": false,
        "id": 2,
        "lines": [
          {
            "speaker": "Quentin",
            "line": "Am I hallucinating?"
          },
          {
            "speaker": "Eliot",
            "line": "If you were, how would asking me help?"
          }
        ]
      },
      {
        "episode": "Unauthorized Magic",
        "explicit": false,
        "id": 4,
        "lines": [
          {
            "speaker": "Quentin",
            "line": "Um... okay... So, \"Be a magician\"? Is that illegal or...? Are you guys trying to take over the world or...?"
          },
          {
            "speaker": "Henry",
            "line": "This school exists for a single and timeless purpose—to reveal your innate abilities and hone them to the highest degree. Now, what you do with it after that is entirely up to you. If you want to take over the world, we don't teach that, but give it a go."
          }
        ]
      },
      {
        "episode": "Unauthorized Magic",
        "explicit": false,
        "id": 5,
        "lines": [
          {
            "speaker": "Eliot",
            "line": "We all signed this waiver. I hope you read yours. It says, \"Spellwork is not unlikely to murder you, and, if so, oh, well.\""
          }
        ]
      },
      {
        "episode": "Unauthorized Magic",
        "explicit": false,
        "id": 6,
        "lines": [
          {
            "speaker": "Quentin",
            "line": "And I really don't want to be the guy who dies in the first ten minutes of the movie because he's like, \"You know what? Let's take out the Ouija board. What could possibly go wrong?\""
          }
        ]
      },
      {
        "episode": "The Source of Magic",
        "explicit": false,
        "id": 7,
        "lines": [
          {
            "speaker": "Pete",
            "line": "You ask a lot of questions."
          },
          {
            "speaker": "Julia",
            "line": "Yeah, I sure do."
          }
        ]
      },
      {
        "episode": "The Source of Magic",
        "explicit": false,
        "id": 8,
        "lines": [
          {
            "speaker": "Quentin",
            "line": "If you're trying to tell me that it gets better—"
          },
          {
            "speaker": "Eliot",
            "line": "Oh, God, no. No, it doesn't. I'm trying to tell you, you are not alone here. Funny little irony they don't tell you. Magic doesn't come from talent. It comes from pain."
          }
        ]
      },
      {
        "episode": "The Source of Magic",
        "explicit": false,
        "id": 13,
        "lines": [
          {
            "speaker": "Quentin",
            "line": "You don't even like me."
          },
          {
            "speaker": "Alice",
            "line": "I don't know you."
          },
          {
            "speaker": "Quentin",
            "line": "I don't know you either, except that we summoned some kind of killer mothman from another world."
          },
          {
            "speaker": "Alice",
            "line": "Yeah, there is that."
          }
        ]
      },
      {
        "episode": "The Source of Magic",
        "explicit": false,
        "id": 9,
        "lines": [
          {
            "speaker": "Julia",
            "line": "Magic is real and that's the thing, and once you know that, you can't—"
          },
          {
            "speaker": "Marina",
            "line": "Nothing else matters."
          },
          {
            "speaker": "Julia",
            "line": "Exactly. It's like... I know it's there. It's everywhere, all around me, a whole world of power and beauty. You can't unsee it. You wake up for the first time."
          }
        ]
      },
      {
        "episode": "The Source of Magic",
        "explicit": false,
        "id": 10,
        "lines": [
          {
            "speaker": "Quentin",
            "line": "Nobody would rather not know. You don't see color and want to go black and white."
          }
        ]
      },
      {
        "episode": "The Source of Magic",
        "explicit": false,
        "id": 11,
        "lines": [
          {
            "speaker": "Quentin",
            "line": "I go back there, and I'm... I'm a depressed super nerd."
          },
          {
            "speaker": "Eliot",
            "line": "How about I find you, and I don't say magic is real, but I do seduce you, and so lift your spirits that life retains its sparkle for decades."
          },
          {
            "speaker": "Quentin",
            "line": "Yeah, that sounds nice. Thank you."
          }
        ]
      },
      {
        "episode": "The Source of Magic",
        "explicit": false,
        "id": 12,
        "lines": [
          {
            "speaker": "Quentin",
            "line": "Is \"Fillory\" real?"
          },
          {
            "speaker": "Jane",
            "line": "Why even ask if you'll just forget it again?"
          },
          {
            "speaker": "Quentin",
            "line": "The books, they're just—they always felt realer than anything."
          },
          {
            "speaker": "Jane",
            "line": "Then it's real."
          }
        ]
      },
      {
        "episode": "Consequences of Advanced Spellcasting",
        "explicit": false,
        "id": 13,
        "lines": [
          {
            "speaker": "Pete",
            "line": "Just don't get too excited. Start slow."
          },
          { "speaker": "Julia", "line": "Yeah, I don't really do slow." }
        ]
      },
      {
        "episode": "Consequences of Advanced Spellcasting",
        "explicit": false,
        "id": 14,
        "lines": [
          {
            "speaker": "Pete",
            "line": "Never gets old, does it? Having a secret. You have magic. They don't. Better than money. Better than sex."
          },
          { "speaker": "Pete", "line": "Well, I guess that one depends." }
        ]
      },
      {
        "episode": "Consequences of Advanced Spellcasting",
        "explicit": false,
        "id": 15,
        "lines": [
          { "speaker": "Quentin", "line": "What's your discipline?" },
          { "speaker": "Alice", "line": "Phosphoromancy. I bend light." },
          { "speaker": "Quentin", "line": "Holy shit!" },
          { "speaker": "Alice", "line": "There are much cooler areas." },
          {
            "speaker": "Quentin",
            "line": "Are you kidding me? You have light bending power. I'm a nothing-mancer. I'm a squat-mancer."
          }
        ]
      },
      {
        "episode": "Consequences of Advanced Spellcasting",
        "explicit": false,
        "id": 17,
        "lines": [
          {
            "speaker": "Julia",
            "line": "So how do you manage it all? Juggling magic and your life?"
          },
          { "speaker": "Marina", "line": "I don't understand the question." },
          {
            "speaker": "Marina",
            "line": "I'm not judging you. I started out like you and you have a good life. Boyfriend. Probably think he keeps you centered. Right?"
          },
          { "speaker": "Julia", "line": "Kinda." },
          {
            "speaker": "Marina",
            "line": "Or, you know, you're keeping him around in case you fail here and need to fall back."
          },
          {
            "speaker": "Marina",
            "line": "All I know... you have to mean it for magic to work. Something clicks when you're all-in, and the real big stuff, you can't do it till you're doing it without a net."
          }
        ]
      },
      {
        "episode": "Consequences of Advanced Spellcasting",
        "explicit": false,
        "id": 18,
        "lines": [
          { "speaker": "Margo", "line": "Where you going, kitty cat?" },
          {
            "speaker": "Alice",
            "line": "I'm done here. For good. You should be happy. Less competition."
          },
          { "speaker": "Margo", "line": "Alice. I like competition." }
        ]
      },
      {
        "episode": "The World in the Walls",
        "explicit": false,
        "id": 19,
        "lines": [
          { "speaker": "Quentin", "line": "Okay, did nobody see that?" },
          { "speaker": "Julia", "line": "See what?" },
          { "speaker": "Quentin", "line": "You laughing at me." },
          {
            "speaker": "Julia",
            "line": "Laughing at you? What kind of a friend would do that?"
          },
          { "speaker": "Quentin", "line": "Exactly." }
        ]
      },
      {
        "episode": "The World in the Walls",
        "explicit": false,
        "id": 20,
        "lines": [
          {
            "speaker": "Eliot",
            "line": "Look, it was a party. He's probably sleeping it off under something, or someone—or someone's thing."
          }
        ]
      },
      {
        "episode": "The World in the Walls",
        "explicit": false,
        "id": 20,
        "lines": [
          {
            "speaker": "Julia",
            "line": "When are you gonna tell me what all this is for?"
          },
          {
            "speaker": "Marina",
            "line": "I did. Bigger, better magic."
          },
          {
            "speaker": "Julia",
            "line": "Yeah, you just never mentioned how."
          },
          {
            "speaker": "Marina",
            "line": "I guess I could tell you now. No, I don't feel like it. Later maybe? Mm, how about never? That's a growing possibility."
          }
        ]
      },
      {
        "episode": "The World in the Walls",
        "explicit": true,
        "id": 21,
        "lines": [
          {
            "speaker": "Marina",
            "line": "Welcome back to Brakebills. Let's go steal their shit."
          }
        ]
      },
      {
        "episode": "The World in the Walls",
        "explicit": false,
        "id": 22,
        "lines": [
          {
            "speaker": "Jane",
            "line": "It doesn't matter what anyone tells you. You make the web you're in. You're the spider and the fly."
          }
        ]
      },
      {
        "episode": "The World in the Walls",
        "explicit": false,
        "id": 23,
        "lines": [
          {
            "speaker": "Quentin",
            "line": "*reading a Fillory and Further book* 'The Madness Maker didn't play for the joy of winning, just the fear of losing. The real curse was, he only played when he could win, which cut him off from the surprise, horror, sadness, and wonder of life. Jane saw only one way out for him: stop playing. Start living.'"
          }
        ]
      },
      {
        "episode": "The World in the Walls",
        "explicit": false,
        "id": 24,
        "lines": [
          {
            "speaker": "Dean Fogg",
            "line": "Quentin, do you really think that the magic that we teach means you get to fly above right and wrong. Magic doesn't solve problems."
          },
          {
            "speaker": "Quentin",
            "line": "It magnifies them"
          }
        ]
      },
      {
        "episode": "The World in the Walls",
        "explicit": false,
        "id": 25,
        "lines": [
          {
            "speaker": "Quentin",
            "line": "I don't need to be taught what magic is or isn't. I need to be taught magic so that I can decide what it is or isn't... for me."
          },
          {
            "speaker": "Dean Fogg",
            "line": "That was almost well put."
          }
        ]
      },
      {
        "episode": "The World in the Walls",
        "explicit": false,
        "id": 26,
        "lines": [
          {
            "speaker": "Marina",
            "line": "Oh, poor you and your taste of honey worse than none at all. You think Brakebills cut you off from magic? You don't know cut off. But baby… You will."
          },
          {
            "speaker": "Dean Fogg",
            "line": "That was almost well put."
          }
        ]
      },
      {
        "episode": "Mendings, Major and Minor",
        "explicit": false,
        "id": 26,
        "lines": [
          {
            "speaker": "Margo",
            "line": "Is Genji your aunt?"
          },
          {
            "speaker": "Eliot",
            "line": "Oh, hey Alice. Is that Genji?"
          },
          {
            "speaker": "Quentin",
            "line": "Do you guys know her?"
          },
          {
            "speaker": "Margo",
            "line": "Everyone does. She runs a retreat. It's like Camp David for magicians."
          },
          {
            "speaker": "Eliot",
            "line": "If Camp David was run by Caligula. *Margo and Eliot chuckle.*"
          },
          {
            "speaker": "Eliot",
            "line": "Stops chuckling when he sees Alice's look of disapproval.* I mean that in the best way."
          }
        ]
      }
    ]
  }
#+end_src

*** Appendix 2 - Literate Programming Magic

Here is the bit of literate programming magic where we put all the code above in the right order and tangle it all to the right files. This is what makes this a /program/, and not just excerpts of code. This re-ordering is also what allowed us throughout this story to discuss the code in any order we wanted, rather than the order the computer wants it in.

What you'll see this as is titles of code blocks, surrounded by ~<<~ and ~>>~ symbols, and arranged into the correct order for the computer,. The titles themselves should be fairly self-explanatory if you check the code blocks throughout the story, but if you want to see the story in the original Org Mode, where the names of each code block are clearly visible, [[https://raw.githubusercontent.com/abbreviatedman/the-magicians-api/main/readme.org][here is the original source code for this entire document]]. And, if you want to just read the code files themselves to see what order they ended up in, [[https://github.com/abbreviatedman/the-magicians-api][check the files at the top of the Git repository for the app]].

#+name: quotes.json
#+begin_src json :tangle data/quotes.json :noweb tangle
  [
    <<epigraph>>,
    <<phosphoromancy-bitches>>
  ]
#+end_src

#+name: other-quotes.json
#+begin_src json :tangle data/other-quotes.json :noweb tangle
  <<other-quotes>>
#+end_src
