* Spellbound

** A Story In Magical Code

by Colin Jaffe

*** Previously, On "Me"

This is a story of the magic of computers, the study of magic, and what happens when people can't or won't or both. It's a true story, all of it, except for the parts from books and TV.

Let's start with some TV to frame things for us.

*Josh:* Previously, on Us…
*Penny:* What?
*Josh:* Just imagine a montage.

That's how Episode 12 of Season 3 of the TV show The Magicians opens. The character of Josh gets to give the recap of what's happened so far, the "Previously, On The Magicians" part, so Penny (and the audience) can get caught up and review the plot threads that this particular episode will pick back up. Of course, he proceeds to review the story so far as most of us would: making himself the main character of the story while throwing in some weird digressions only he would care about.

We'll get back to The Magicians soon. But first. Ahem.

Previously, on Me…

-----

***** Jenny

"Only one man really loved me, and he's dead," my fiancé practically screamed, and my heart broke, for her and for me.

Jenny's father died when she was a teen—this was who she was talking about, the man who'd loved her until the day he'd died. She certainly wasn't talking about me, alive and sitting on the couch next to her in our small apartment in Syracuse, my computer in my lap and no words coming to my lips. I was probably between online poker tournaments at the time. That, or playing World of Warcraft.

/I can't blame her for feeling that way,/ I thought. I had not made her feel loved lately, what with spending near every waking hour playing poker or Warcraft. I sat there for a moment after she said it, frozen, shut down; eventually I would come to describe that feeling I get sometimes in even more robotic terms, as "my gears grinding". A feeling of heat in my head, my thoughts slowing, somehow stopping.

Now, of course, she had /practically/ screamed it, but she hadn't /actually/ screamed. As two nerdy white people who grew up middle-class-plus, by the time we were adults we had internalized that you do /not/ cause a scene. And she might of course have been feeding off my non-energy—expressing yourself deeply is harder when you're accustomed to not talking much at all.

"I'm sorry," I managed, eventually. It felt like acceptance, an acknowledgement that this relationship was ending, or had already ended and was now being properly categorized.

I moved in with my parents while she thought things through. Before too long, the wedding was off, the relationship over, and my 20s near an end.

This is not an uncommon story, here. Guy In His 20s Is Kind Of A Loser, Woman Spends More Time With Him Than Is Wise. I certainly did /feel/ like a loser. Had I /wanted/ the relationship to fail? If not, if I cared about her, if I cared about /anything/ except what was right in front of me at any given moment, then why did I not goddamn /act/ like it?

I wouldn't properly grapple with these questions for another decade plus, but when I would, it would be a journey backwards through family history and modern psychiatric history, and a journey forwards, unsteadily, on a quest to find work a prehistoric brain can do in late-stage capitalism and a home outside my own head.

***** My First Job

My parents, knowing their high-school-aged son was into computers, suggested The Computer Museum downtown might be hiring and make a good first job. I filled out an application, and got called for an interview, and went in, and got the job. I remember a handshake—it made a big impression on me. I had done so many adult things by myself, and now I had a job of my own.

Throughout my high school summers—and the year after I graduated, when I took a "year" off before college—I answered visitor questions, watched the exhibits for anything getting out of order, and, soon enough, was trusted to run presentations and classes. This was '95 and '96, so every time I taught  a class on "How To Use The Internet", the room was full of visitors gawking at this little growing world that seemed occasionally quite useful, while I demonstrated that you didn't /have/ to write "http://" in browsers, even if people gave you an address that included it.

That class was my first teaching experience, and it was a good one, but what I loved most was being the Robot in the Teach a Robot How To Make A Peanut Butter and Jelly Sandwich demonstration. I found I had a particular skill for being literal-minded, which was what the person being the Robot needed, and so I was always the Robot. I sat at a table, which was laid out with a jar of a peanut butter, a jar of jelly, a bagged loaf of bread, a plate, and a butter knife. My partner in the activity would ask the audience to submit directions for the robot and pass them on to me. I would then interpret each directions as a computer would, following the direction to the letter and inferring nothing. "Put the peanut butter on the bread!" would result in the jar, unopened, placed atop the loaf. Once the jar and bread bag were opened, "Get the peanut butter out and spread it on the bread," would leave my hands covered in Crunchy Jiff—my commitment to the bit was complete and all-consuming, joyful and effortless. The audience learned slowly, somewhat, how to think like a robot, but I didn't learn so much as tap in. I was a Robot, and a Robot was me.

I might still be executing commands and making messy sandwiches , but The Computer Museum ran out of money—there was talk it had been embezzled by an employee, but whatever the cause, it got shut down, with some of the valuable electronic museum pieces bought by the Museum of Science.

Down the line, I would end up working at the Museum of Science. But those old computers—including an early Apple computer and a piece of the ancient building-sized ENIAC machine—would be packed away in the back, because they didn't fit in there at the new museum. The Museum of Science was all about interacting with exhibits that cleverly mirrored the hidden scientific principles of the world, for exploring the ways the world works and the ways we learn about the world. It was not a museum for plaques in front of historically important but non-functioning machines. It was a not a museum either for sandwich-making humans.

***** Jobs

The montage speeds up, covering a couple of decades in a burst of scenes. Rapid-fire firings along with quits so fast I'd barely started—an unemployment history, like a negative resume. The weather calls for a flurry of disappointed supervisors, so grab some shelter. It's about to hail.

-----

Our heroes reaching the summit in their climb up Mt. Everest in the Museum of Science's IMAX Theater presentation was an exhilarating and triumphant cinematic moment and also so so boring the literal 100th time you witnessed it. Unlike the Computer Museum, the Museum of Science is a seriously great museum and a greatly serious place of employment. They were not going to put up with me falling asleep every time from the 83rd viewing on. And they didn't.

This was my first firing.

-----

I was skilled at telephone outreach, particularly for good causes, so The Share Group, which called to re-up donors to Greenpeace and Emily's List and countless other progressive groups, seemed a good place for me. But I couldn't stay locked in on phone call after phone call when the people sitting next to me were even half-way decent conversationalists. I argued repeatedly with management that I in fact had been on the phone the whole time, unabashed and unchastened.

They were a union shop, and it was tough to get fired there, even if you were often unproductive and mildly belligerent about it. They waited until I finally went off to college, and then they could simply not re-hire me. Problem solved.

-----

"Is there an explanation for why you didn't do the tasks I assigned you?" my boss at CPPAX asked. Citizens for Participation in Public Action was the first organization to promote me. Do you know the Peter Principle? People tend to get promoted due to competence in their roles, until they reach a role where those skills they have don't really translate. And then they tend to stay there. You tend to rise to your "level of respective incompetence".

I shook my head, ashamed, no real answer to give. I had been promoted from telephone fundraiser, which I was good at, to a role wrangling donor data, which I might've been good at if I could focus on the spreadsheets for more than a minute at a time. Is there a Principle for being promoted until you just /can't even/ with the work?

She demoted me after our "talk", back to talking to donors, but my heart was broken. Or something else. Not quite my pride, but something definitely was broken. This was a "You can't fire me, I quit weeks ago," kind of ending. Or perhaps it doesn't matter that I don't even remember if I quit or got fired—it was mutual either way.

-----

One of the most painful jobs I ever had was working the counter at a Burger King in Syracuse. Orders came in quickly and had to be routed to the right teammates, while the returning food had to be routed back to the right customers, all of whom had waited with varying degrees of patience while I thought back through the maze of interweaving  events like a detective at the end of a mystery film. My boss appeared to be very proud of himself when, after a particularly rough shift of customers angry at my harried slowness, he told me that at Burger King, "We don't discriminate." It took me until after the shift to calm down enough to think about what he'd said and realize that he thought he was being very gracious to a man with a severe intellectual disability. This struck me at the time as a funny comment on how bad I was at multi-tasking, and certainly not a sign of deeper issues.

Anyway, I was late one too many times, and you can only bend so far for someone who basically can't do the job. This one was very much a firing.

-----


- AnnieCannons
- Frank's Convenient
- Ripen With Us
- Balloon Art
- Stormwind

***** Ritalin

"I just feel /too/ focused," I told my mom. "I feel boring, like I'm not thinking enough. I don't like it."

Picture a young man at 15. Short, with a poorly maintained goatee. You know the type, I'm sure.

My mom and I were discussing whether Ritalin was helping me—I had been taking it for a good while at that point. The doctors said I had ADD, which was what people back then called the type of ADHD without Hyperactivity. This is the type of ADD that is harder to pinpoint, since I wasn't doing the highly-visible thing of constantly moving my body everywhere. I was quite able to focus in fact—I simply focused on the wrong things. During most classes that year I would write computer code in my notebook, putting pencil to paper in those innocent days before laptops in schools. Most of the time, the teachers trusted that I was taking notes. All of the time, I wasn't. I wasn't even chastened or ashamed to be spoken to when caught—just frustrated at having to temporarily stop.

We have selective memory—we humans, and especially those with ADD. While I remember a silly amount of the code I wrote at the time, I do /not/ remember whether Ritalin was, in fact, affecting my state of mind at all, and definitely not if it made me feel, as I told my mom, that I wasn't "thinking enough". Do people sometimes think at different speeds or amounts? Knowing this would take a certain kind of metacognition, of noticing your own thinking, that I've never been good at.

What I /am/ good at, at least sometimes, is figuring out what people want to hear, so maybe that was all I was doing when talking about my experience with Ritalin—appealing to that peculiar cultural concept of the '90s, the sense that maybe we were overmedicating kids for just being /kids/. Ritalin, I was arguing, was turning me into a robot instead of letting me be myself, and boy /howdy/ did we gobble up that trope in the '90s.

Whether it was what I said or the rather salient fact that my grades weren't improving from the B-D range, my parents took me off Ritalin not too long after.

As I grew up, I heard less and less about ADD. If I thought about it at all, it was easily dismissed. I wasn't some hyperactive /kid/, and I'd never really been hyperactive to begin with.

***** Poker

The World Series of Poker was on TV, and it's estimated that 100% of the students I knew at Hampshire College were watching it. Mostly because the only students I knew were the ones in our almost-off-campus little house, and whenever poker was on, I would watch it on the only TV in the place. It was the Fall of 2003, and poker was a really big deal elsewhere in America, too. ESPN greatly expanded their coverage of the World Series of Poker, and it led to a rise in online poker—by the time the 2004 event rolled around, the number of participants had tripled.

When Chris Moneymaker (yes, his real name) won it all in '03 as a real everyman, a plain-faced accountant, it gave birth to "the Moneymaker effect", and suddenly a certain kind of person seemed to think they could make money playing poker. I was not only that certain kind of person, but I became convinced I could take advantage of the other members of that certain kind.

I blew off my studies to play poker with my housemates, particularly Ed Peduzzi, a film student at Hampshire. I learned a lot from Ed—mostly that you had to be careful about bluffing when someone was likely to call you unwisely, which Ed was. Which most people were. Are.

I dropped out of Hampshire after that semester, but I don't blame poker. I wasn't even blowing off studies really that semester—I was blowing off watching the Red Sox in the playoffs, and in turn watching that would've been blowing off something else. My studies, such as they were at that point, were pretty far down the list.

I had spent the entirety of the years I was with Jenny in a series of jobs I took as they presented themselves to me, filling in time between them with online poker, a game I was just good enough at to make a meager and stressful living playing. Poker always paid the bills except when it didn't. The game was good for me in that I answered to no one—a good thing since I was and remain very poor at following directions, meeting deadlines, being on time, and doing things I'm not 100% sold on. These, it turns out, are rather important for functioning within a group of people, which is why I spent time when I was working at a more /job/ type of job saving up money. When I had enough saved, I would either quit or wait for the job to tire of my shtick and fire me. Then I would use those savings to make more money in poker, always leaving that saved-up money as a cushion for small runs of bad luck. I could /usually/ get back to winning and paying rent before the cushion ran out. Like I said, it was a meager and stressful living, and that was when things went well. I would always end up looking for a job again when a bad poker luck run cost me more than my cushion.

So: not exactly the breadwinner, here. Jenny herself didn't make a ton of money, as she was living on loans to get herself through a pair of graduate degrees that started esoteric (Classical Music Composition) and moved to academic-but-at-least-eventually-financially-viable (Library Science). What's more, I was playing even less poker at the time and thus making even less money, as I was heavily into computer gaming. Or, rather, one particular game—Jenny had gotten me hooked on World of Warcraft, an endless online game, a bit like Dungeons and Dragons if you took out all social interaction except what you need to satisfy that part of your brain, and then took out all the creative storytelling of D&D as well. Jenny had thought I could handle the game; I'd gone along with her insistence I join her World of Warcraft guild even though I knew I couldn't. She probably thought it would bring us closer together. Maybe I believed this too, despite myself, but I just went from the laser-sharp focus of playing poker to the laser-sharp focus of gaming.

So when she almost-screamed at me that I didn't love her, I felt like I couldn't disagree. The evidence was against me. I /felt/ like I loved her, but I had spent the time since we'd gotten engaged doing less and less to prove it every day. Was that itself just another game to me, to see what I could get away with? What she'd stick with me through?

Was I lazy, or neglectful bordering on abusive, or thoughtless, or nihilistic, or depressive?

I could only answer that question with a big "Yes". I apologized for the hurt I'd caused and moved back in with my parents. The wedding wasn't called off quite yet, but when she realized how much happier she was without me around, it was. Or had, in a sense, never truly been on the docket to begin with.

*** Note For Reviewers

This is a half-finished introductory chapter to a memoir, or at least a memoir-ish… thing. Eventually it will explore the form itself—for now, treat it as a simple memoir.

The themes include or will include:

- ADHD in adults
- parenting a kid with ADHD with ADHD (yes, that repetition is on purpose)
- coding
- literature and stories
- failing in conventional measures of success and succeeding in ways unconventional

*** Chapter 1 - Unauthorized Magic

*** Appendix 1 - The Rest Of The Code

Here is the code for the app that I don't plan to discuss—or haven't yet. It's the Magicians quotes that make up the app but aren't relevant to the story, or uninteresting parts of the code that didn't merit discussion, or a part whose discussion didn't /quite/ fit in the story, or just code I've written for the app that I haven't figured out how to weave in yet.

This section is really just for those coders curious about the rest of the code.

Enjoy?

#+name: other-quotes
#+begin_src json
  {
    "quotes": [
      {
        "episode": "Unauthorized Magic",
        "explicit": false,
        "id": 0,
        "lines": [
          {
            "speaker": "Quentin",
            "line": "I mean, I get it."
          },
          {
            "speaker": "Dr. London",
            "line": "Get...?"
          },
          {
            "speaker": "Quentin",
            "line": "You're a kid, and your whole life's ahead of you, and you have these notions... about what life is... and... what it could be. But eventually you have to let all that go. So that's what I'm... That's what I'm going to do... that's what I'm doing. Um, it's a part of growing up... You know, selling the comic-book collection and getting serious."
          }
        ]
      },
      {
        "episode": "Unauthorized Magic",
        "explicit": false,
        "id": 1,
        "lines": [
          {
            "speaker": "Quentin",
            "line": "And, honestly, they probably take anyone conscious for philosophy."
          },
          {
            "speaker": "Julia",
            "line": "For philosophy, \"conscious\" is a detriment."
          }
        ]
      },
      {
        "episode": "Unauthorized Magic",
        "explicit": false,
        "id": 2,
        "lines": [
          {
            "speaker": "Quentin",
            "line": "Am I hallucinating?"
          },
          {
            "speaker": "Eliot",
            "line": "If you were, how would asking me help?"
          }
        ]
      },
      {
        "season": 1,
        "episode": 1,
        "explicit": true,
        "id": 3,
        "lines": [
          {
            "speaker": "Henry Fogg",
            "line": "You want to go back to Columbia? That pointless, miasmic march to death you call life? Family that never calls and friends that don't really get you and feeling alone and wrong until it crushes you?"
          },
          {
            "speaker": "Quentin",
            "line": "No."
          },
          {
            "speaker": "Henry Fogg",
            "line": "Then quit dicking around!"
          },
          {
            "speaker": "Quentin",
            "line": "Stop it."
          },
          {
            "speaker": "Henry Fogg",
            "line": "Do some goddamn magic!"
          }
        ]
      },
      {
        "episode": "Unauthorized Magic",
        "explicit": false,
        "id": 4,
        "lines": [
          {
            "speaker": "Quentin",
            "line": "Um... okay... So, \"Be a magician\"? Is that illegal or...? Are you guys trying to take over the world or...?"
          },
          {
            "speaker": "Henry",
            "line": "This school exists for a single and timeless purpose—to reveal your innate abilities and hone them to the highest degree. Now, what you do with it after that is entirely up to you. If you want to take over the world, we don't teach that, but give it a go."
          }
        ]
      },
      {
        "episode": "Unauthorized Magic",
        "explicit": false,
        "id": 5,
        "lines": [
          {
            "speaker": "Eliot",
            "line": "We all signed this waiver. I hope you read yours. It says, \"Spellwork is not unlikely to murder you, and, if so, oh, well.\""
          }
        ]
      },
      {
        "episode": "Unauthorized Magic",
        "explicit": false,
        "id": 6,
        "lines": [
          {
            "speaker": "Quentin",
            "line": "And I really don't want to be the guy who dies in the first ten minutes of the movie because he's like, \"You know what? Let's take out the Ouija board. What could possibly go wrong?\""
          }
        ]
      },
      {
        "episode": "The Source of Magic",
        "explicit": false,
        "id": 7,
        "lines": [
          {
            "speaker": "Pete",
            "line": "You ask a lot of questions."
          },
          {
            "speaker": "Julia",
            "line": "Yeah, I sure do."
          }
        ]
      },
      {
        "episode": "The Source of Magic",
        "explicit": false,
        "id": 8,
        "lines": [
          {
            "speaker": "Quentin",
            "line": "If you're trying to tell me that it gets better—"
          },
          {
            "speaker": "Eliot",
            "line": "Oh, God, no. No, it doesn't. I'm trying to tell you, you are not alone here. Funny little irony they don't tell you. Magic doesn't come from talent. It comes from pain."
          }
        ]
      },
      {
        "episode": "The Source of Magic",
        "explicit": false,
        "id": 13,
        "lines": [
          {
            "speaker": "Quentin",
            "line": "You don't even like me."
          },
          {
            "speaker": "Alice",
            "line": "I don't know you."
          },
          {
            "speaker": "Quentin",
            "line": "I don't know you either, except that we summoned some kind of killer mothman from another world."
          },
          {
            "speaker": "Alice",
            "line": "Yeah, there is that."
          }
        ]
      },
      {
        "episode": "The Source of Magic",
        "explicit": false,
        "id": 9,
        "lines": [
          {
            "speaker": "Julia",
            "line": "Magic is real and that's the thing, and once you know that, you can't—"
          },
          {
            "speaker": "Marina",
            "line": "Nothing else matters."
          },
          {
            "speaker": "Julia",
            "line": "Exactly. It's like... I know it's there. It's everywhere, all around me, a whole world of power and beauty. You can't unsee it. You wake up for the first time."
          }
        ]
      },
      {
        "episode": "The Source of Magic",
        "explicit": false,
        "id": 10,
        "lines": [
          {
            "speaker": "Quentin",
            "line": "Nobody would rather not know. You don't see color and want to go black and white."
          }
        ]
      },
      {
        "episode": "The Source of Magic",
        "explicit": false,
        "id": 11,
        "lines": [
          {
            "speaker": "Quentin",
            "line": "I go back there, and I'm... I'm a depressed super nerd."
          },
          {
            "speaker": "Eliot",
            "line": "How about I find you, and I don't say magic is real, but I do seduce you, and so lift your spirits that life retains its sparkle for decades."
          },
          {
            "speaker": "Quentin",
            "line": "Yeah, that sounds nice. Thank you."
          }
        ]
      },
      {
        "episode": "The Source of Magic",
        "explicit": false,
        "id": 12,
        "lines": [
          {
            "speaker": "Quentin",
            "line": "Is \"Fillory\" real?"
          },
          {
            "speaker": "Jane",
            "line": "Why even ask if you'll just forget it again?"
          },
          {
            "speaker": "Quentin",
            "line": "The books, they're just—they always felt realer than anything."
          },
          {
            "speaker": "Jane",
            "line": "Then it's real."
          }
        ]
      },
      {
        "episode": "Consequences of Advanced Spellcasting",
        "explicit": false,
        "id": 13,
        "lines": [
          {
            "speaker": "Pete",
            "line": "Just don't get too excited. Start slow."
          },
          { "speaker": "Julia", "line": "Yeah, I don't really do slow." }
        ]
      },
      {
        "episode": "Consequences of Advanced Spellcasting",
        "explicit": false,
        "id": 14,
        "lines": [
          {
            "speaker": "Pete",
            "line": "Never gets old, does it? Having a secret. You have magic. They don't. Better than money. Better than sex."
          },
          { "speaker": "Pete", "line": "Well, I guess that one depends." }
        ]
      },
      {
        "episode": "Consequences of Advanced Spellcasting",
        "explicit": false,
        "id": 15,
        "lines": [
          { "speaker": "Quentin", "line": "What's your discipline?" },
          { "speaker": "Alice", "line": "Phosphoromancy. I bend light." },
          { "speaker": "Quentin", "line": "Holy shit!" },
          { "speaker": "Alice", "line": "There are much cooler areas." },
          {
            "speaker": "Quentin",
            "line": "Are you kidding me? You have light bending power. I'm a nothing-mancer. I'm a squat-mancer."
          }
        ]
      },

        "season": 1,
        "episode": 3,
        "explicit": true,
        "id": 16,
        "lines": [
          {
            "speaker": "Quentin",
            "line": "Phosphoromancy, bitches."
          }
        ]
      }
      {
        "episode": "Consequences of Advanced Spellcasting",
        "explicit": false,
        "id": 17,
        "lines": [
          {
            "speaker": "Julia",
            "line": "So how do you manage it all? Juggling magic and your life?"
          },
          { "speaker": "Marina", "line": "I don't understand the question." },
          {
            "speaker": "Marina",
            "line": "I'm not judging you. I started out like you and you have a good life. Boyfriend. Probably think he keeps you centered. Right?"
          },
          { "speaker": "Julia", "line": "Kinda." },
          {
            "speaker": "Marina",
            "line": "Or, you know, you're keeping him around in case you fail here and need to fall back."
          },
          {
            "speaker": "Marina",
            "line": "All I know... you have to mean it for magic to work. Something clicks when you're all-in, and the real big stuff, you can't do it till you're doing it without a net."
          }
        ]
      },
      {
        "episode": "Consequences of Advanced Spellcasting",
        "explicit": false,
        "id": 18,
        "lines": [
          { "speaker": "Margo", "line": "Where you going, kitty cat?" },
          {
            "speaker": "Alice",
            "line": "I'm done here. For good. You should be happy. Less competition."
          },
          { "speaker": "Margo", "line": "Alice. I like competition." }
        ]
      },
      {
        "episode": "The World in the Walls",
        "explicit": false,
        "id": 19,
        "lines": [
          { "speaker": "Quentin", "line": "Okay, did nobody see that?" },
          { "speaker": "Julia", "line": "See what?" },
          { "speaker": "Quentin", "line": "You laughing at me." },
          {
            "speaker": "Julia",
            "line": "Laughing at you? What kind of a friend would do that?"
          },
          { "speaker": "Quentin", "line": "Exactly." }
        ]
      },
      {
        "episode": "The World in the Walls",
        "explicit": false,
        "id": 20,
        "lines": [
          {
            "speaker": "Eliot",
            "line": "Look, it was a party. He's probably sleeping it off under something, or someone—or someone's thing."
          }
        ]
      },
      {
        "episode": "The World in the Walls",
        "explicit": false,
        "id": 20,
        "lines": [
          {
            "speaker": "Julia",
            "line": "When are you gonna tell me what all this is for?"
          },
          {
            "speaker": "Marina",
            "line": "I did. Bigger, better magic."
          },
          {
            "speaker": "Julia",
            "line": "Yeah, you just never mentioned how."
          },
          {
            "speaker": "Marina",
            "line": "I guess I could tell you now. No, I don't feel like it. Later maybe? Mm, how about never? That's a growing possibility."
          }
        ]
      },
      {
        "episode": "The World in the Walls",
        "explicit": true,
        "id": 21,
        "lines": [
          {
            "speaker": "Marina",
            "line": "Welcome back to Brakebills. Let's go steal their shit."
          }
        ]
      },
      {
        "episode": "The World in the Walls",
        "explicit": false,
        "id": 22,
        "lines": [
          {
            "speaker": "Jane",
            "line": "It doesn't matter what anyone tells you. You make the web you're in. You're the spider and the fly."
          }
        ]
      },
      {
        "episode": "The World in the Walls",
        "explicit": false,
        "id": 23,
        "lines": [
          {
            "speaker": "Quentin",
            "line": "*reading a Fillory and Further book* 'The Madness Maker didn't play for the joy of winning, just the fear of losing. The real curse was, he only played when he could win, which cut him off from the surprise, horror, sadness, and wonder of life. Jane saw only one way out for him: stop playing. Start living.'"
          }
        ]
      },
      {
        "episode": "The World in the Walls",
        "explicit": false,
        "id": 24,
        "lines": [
          {
            "speaker": "Dean Fogg",
            "line": "Quentin, do you really think that the magic that we teach means you get to fly above right and wrong. Magic doesn't solve problems."
          },
          {
            "speaker": "Quentin",
            "line": "It magnifies them"
          }
        ]
      },
      {
        "episode": "The World in the Walls",
        "explicit": false,
        "id": 25,
        "lines": [
          {
            "speaker": "Quentin",
            "line": "I don't need to be taught what magic is or isn't. I need to be taught magic so that I can decide what it is or isn't... for me."
          },
          {
            "speaker": "Dean Fogg",
            "line": "That was almost well put."
          }
        ]
      },
      {
        "episode": "The World in the Walls",
        "explicit": false,
        "id": 26,
        "lines": [
          {
            "speaker": "Marina",
            "line": "Oh, poor you and your taste of honey worse than none at all. You think Brakebills cut you off from magic? You don't know cut off. But baby… You will."
          },
          {
            "speaker": "Dean Fogg",
            "line": "That was almost well put."
          }
        ]
      },
      {
        "episode": "Mendings, Major and Minor",
        "explicit": false,
        "id": 26,
        "lines": [
          {
            "speaker": "Margo",
            "line": "Is Genji your aunt?"
          },
          {
            "speaker": "Eliot",
            "line": "Oh, hey Alice. Is that Genji?"
          },
          {
            "speaker": "Quentin",
            "line": "Do you guys know her?"
          },
          {
            "speaker": "Margo",
            "line": "Everyone does. She runs a retreat. It's like Camp David for magicians."
          },
          {
            "speaker": "Eliot",
            "line": "If Camp David was run by Caligula. *Margo and Eliot chuckle.*"
          },
          {
            "speaker": "Eliot",
            "line": "Stops chuckling when he sees Alice's look of disapproval.* I mean that in the best way."
          }
        ]
      }
    ]
  }
#+end_src

*** Appendix 3 - Unused Writing

I may work this back into the book if there's a place for it, but here is a mostly-done story about the actual worst job I ever had. The ending will be written when I get a chance, but if you're curious what happens: I get pee on me and hate it and leave a note on the door and never set foot in the place again.

**** Frank Is Convenient

The most painful job I ever had was at a gas station and convenience store in Buffalo. It's closed now, but you can still find it on Google Maps under Frank's Convenience. But the sign said Frank's Convenient—still says it in the picture on Google, in fact. And he /was/ convenient as an employer, in that he was down the street from the apartment Jenny and I were staying in—not the apartment where she would scream at me, though we'll come back to that apartment soon enough.

That area of Buffalo was very much a college area, so while I had to take occasional payment for gas from drivers looking to save 10 cents a gallon by paying in cash, the majority of my work was selling beer to college kids. And when a party night came around, those kids came in a dozen at a time, and I rang them up one at a time, slowly and effortfully. (One takeaway here: I do not think quickly.)

Not only did I have to ring up all those college folk, but on particularly wild nights, we would start to run out of beer in the fridge, and I'd have to restock from the back. I'd walk behind the fridges, to the big stacks of beer boxes, take the right ones down, open the back doors to the fridges, and put them in for the kids to take, like a rarely-glimpsed beer elf who lived in the walls.

And, of course, I had to manage the store in general while doing this—maintain the coffee and Slurpee machines, keep an eye out for shoplifters, answer questions as to where something was, and so on. (Another takeaway: I cannot "and so on" very well.)

Well, one night, things got real hectic real fast, and towards the end of the night, around 2:30am, I was loading beer into the backs of the fridges when one of boxes slipped from my grasp and crashed to the floor. I went to pick up the carton and cut myself on one of the bottles—It was broken, spilling beer on the floor and on my shoes and spilling blood from my finger.

I loaded a fresh carton in to the fridge and made my way back to the counter, my shoes grasping the floor with every step thanks to the spilled beer stuck to their soles. I grabbed a napkin and held it to my finger to staunch the bleeding, which was fortunately minor. I thought I had gotten through the worst of the night, with the crowd dying down somewhat and the line of would-be party-goers slowly slowly getting shorter, when, around 2:45, just as the 3:00 closing time felt so near, someone came up to the counter and told me the toilet was clogged.

I asked forgiveness of the customer in front of me and stepped away to check out the bathroom. The toilet was close to overflowing with pee. My brain was close to overflowing at that point too, so I figured I'd get the last customers and then close the store and /then/ clean up the beer and unclog the toilet.
*** Appendix 2 - Literate Programming Magic

Here is the bit of literate programming magic where we put all the code above in the right order and tangle it all to the right files. This is what makes this a /program/, and not just excerpts of code. This re-ordering is also what allowed us throughout this story to discuss the code in any order we wanted, rather than the order the computer wants it in.

What you'll see this as is titles of code blocks, surrounded by ~<<~ and ~>>~ symbols, and arranged into the correct order for the computer,. The titles themselves should be fairly self-explanatory if you check the code blocks throughout the story, but if you want to see the story in the original Org Mode, where the names of each code block are clearly visible, [[https://raw.githubusercontent.com/abbreviatedman/the-magicians-api/main/readme.org][here is the original source code for this entire document]]. And, if you want to just read the code files themselves to see what order they ended up in, [[https://github.com/abbreviatedman/the-magicians-api][check the files at the top of the Git repository for the app]].

#+name: quotes.json
#+begin_src json :tangle data/quotes.json :noweb tangle
  []
#+end_src

#+name: other-quotes.json
#+begin_src json :tangle data/other-quotes.json :noweb tangle
  <<other-quotes>>
#+end_src
